package com.cyp.models;
// Generated Nov 2, 2022, 9:08:10 PM by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;

/**
 * Cb generated by hbm2java
 */
public class Cb implements java.io.Serializable {

	private Integer idcb;
	private int num;
	private String date;
	private int cryptogramme;
	private BigDecimal solde;

	public Cb() {
	}

	public Cb(int num, String date, int cryptogramme, BigDecimal solde) {
		this.num = num;
		this.date = date;
		this.cryptogramme = cryptogramme;
		this.solde = solde;
	}

	public Integer getIdcb() {
		return this.idcb;
	}

	public void setIdcb(Integer idcb) {
		this.idcb = idcb;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public int getCryptogramme() {
		return this.cryptogramme;
	}

	public void setCryptogramme(int cryptogramme) {
		this.cryptogramme = cryptogramme;
	}

	public BigDecimal getSolde() {
		return this.solde;
	}

	public void setSolde(BigDecimal solde) {
		this.solde = solde;
	}

}
