package com.cyp.models;
// Generated Nov 2, 2022, 12:09:31 PM by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;

/**
 * Cb generated by hbm2java
 */
public class Cb implements java.io.Serializable {

	private Integer idcb;
	private Long num;
	private String nom;
	private String date;
	private int cryptogramme;
	private BigDecimal solde;

	public Cb() {
	}

	public Cb(Long num, String nom, String date, int cryptogramme, BigDecimal solde) {
		this.num = num;
		this.nom = nom;
		this.date = date;
		this.cryptogramme = cryptogramme;
		this.solde = solde;
	}

	public Integer getIdcb() {
		return this.idcb;
	}

	public void setIdcb(Integer idcb) {
		this.idcb = idcb;
	}

	public Long getNum() {
		return this.num;
	}

	public void setNum(Long num) {
		this.num = num;
	}
	
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public int getCryptogramme() {
		return this.cryptogramme;
	}

	public void setCryptogramme(int cryptogramme) {
		this.cryptogramme = cryptogramme;
	}

	public BigDecimal getSolde() {
		return this.solde;
	}

	public void setSolde(BigDecimal solde) {
		this.solde = solde;
	}

}
