package com.cyp.models;
// Generated Nov 2, 2022, 12:09:31 PM by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;

/**
 * Produit generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idproduit;
	private String nom;
	private BigDecimal prix;
	private int quantite;
	private String description;
	private String url;

	public Produit() {
	}

	public Produit(BigDecimal prix, int quantite) {
		this.prix = prix;
		this.quantite = quantite;
	}

	public Produit(String nom, BigDecimal prix, int quantite, String description, String url) {
		this.nom = nom;
		this.prix = prix;
		this.quantite = quantite;
		this.description = description;
		this.url = url;
	}

	public Integer getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(Integer idproduit) {
		this.idproduit = idproduit;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
