package com.cyp.models;
// Generated Nov 2, 2022, 12:09:31 PM by Hibernate Tools 5.4.33.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer idclient;
	private String nom;
	private String prenom;
	private String mail;
	private String adresse;
	private Byte estconnecte;
	private String role;
	private byte passerCommande;
	private byte payerCommande;
	private String mdp;

	public User() {
	}

	public User(String nom, String prenom, String mail, String adresse, String role, byte passerCommande,
			byte payerCommande, String mdp) {
		this.nom = nom;
		this.prenom = prenom;
		this.mail = mail;
		this.adresse = adresse;
		this.role = role;
		this.passerCommande = passerCommande;
		this.payerCommande = payerCommande;
		this.mdp = mdp;
	}

	public User(String nom, String prenom, String mail, String adresse, Byte estconnecte, String role,
			byte passerCommande, byte payerCommande, String mdp) {
		this.nom = nom;
		this.prenom = prenom;
		this.mail = mail;
		this.adresse = adresse;
		this.estconnecte = estconnecte;
		this.role = role;
		this.passerCommande = passerCommande;
		this.payerCommande = payerCommande;
		this.mdp = mdp;
	}

	public Integer getIdclient() {
		return this.idclient;
	}

	public void setIdclient(Integer idclient) {
		this.idclient = idclient;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Byte getEstconnecte() {
		return this.estconnecte;
	}

	public void setEstconnecte(Byte estconnecte) {
		this.estconnecte = estconnecte;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public byte getPasserCommande() {
		return this.passerCommande;
	}

	public void setPasserCommande(byte passerCommande) {
		this.passerCommande = passerCommande;
	}

	public byte getPayerCommande() {
		return this.payerCommande;
	}

	public void setPayerCommande(byte payerCommande) {
		this.payerCommande = payerCommande;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

}
